// v2.1 JOURNAL lane: reward track 10/25/40, family rewards, titles, Sparkle Meter jar, Breeds & Mixes, pen-pal schedule, postcard album, Profile ancestry.
// PAW_ARGS=--ignore-certificate-errors NODE_PATH=$(npm root -g) node game/run_tests.js game/test_v21_journal.js --jobs 1
require('./test_lib').run('v21_journal', async (t) => {
  const { ok, sec, ev, S } = t;
  sec('new game');
  const s0 = await t.newGame({}, { coins: 1000 });
  const p = t.p, me = s0.dog.id;
  const ago = (n) => ev((n) => { const d = new Date(); d.setDate(d.getDate() - n); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }, n);
  const openJ = async (tab) => { await p.click('[data-act=journal]'); await p.waitForSelector('.panel.journal'); await p.click(`[data-jt=${tab}]`); await p.waitForSelector(`.panel.journal.j-${tab}`); };
  const closeAll = async () => { await t.closeX(); await t.modalGone(); };
  const setBook = (n) => ev((n) => { const S = window.__paw.S; const b = {}; for (let i = 0; i < n; i++) b['corgi|Fake Coat ' + i] = '2026-01-01'; S.coatBook = b; }, n);

  sec('reward track: 10 / 25 / 40, each once');
  await ev(() => { window.__paw.S.coatRewards = {}; window.__paw.S.title = ''; window.__paw.S.titles = {}; });
  await setBook(8); // plus the dog at home = 9
  await openJ('coats'); await p.waitForSelector('.ctop');
  let s = await S();
  ok(!s.coatRewards[10] && !(s.titles || {})['Gene Detective'], '9 coats: no Gene Detective yet');
  await closeAll(); await setBook(9);
  await openJ('coats'); await p.waitForSelector('.ctop'); s = await S(); const coins10 = s.coins;
  ok(!!s.coatRewards[10] && !!s.titles['Gene Detective'] && s.title === 'Gene Detective', '10 coats: title Gene Detective (shown on the name tag)');
  ok(await t.waitToast(/Gene Detective/), 'title toast');
  ok(await p.textContent('#hudTitle') === 'Gene Detective', 'HUD name tag shows the title');
  await closeAll(); await openJ('coats'); await p.waitForSelector('.ctop'); s = await S();
  ok(s.coins === coins10 && Object.keys(s.titles).length === 1, 'reopening gives nothing more');
  await closeAll();
  ok(!s.inv.clothes.includes('Rainbow Collar'), 'no Rainbow Collar below 25');
  await setBook(24); await openJ('coats'); await p.waitForSelector('.ctop'); s = await S();
  ok(!!s.coatRewards[25] && s.inv.clothes.filter((c) => c === 'Rainbow Collar').length === 1, '25 coats: Rainbow Collar in the wardrobe inventory');
  ok(!!s.coatRewards[15] && !!s.coatRewards[5], '5 and 15 on the way');
  await closeAll();
  await p.click('[data-act=wardrobe]'); await p.waitForSelector('.ward');
  ok(await p.locator('[data-eq="Rainbow Collar"]').count() === 1, 'Wardrobe lists the Rainbow Collar');
  await closeAll();
  await t.home('market'); await p.click('#placeBtns [data-sh=boutique]'); await p.waitForSelector('[data-buy]');
  ok(await p.locator('[data-buy="Rainbow Collar"]').count() === 0, 'Boutique does not sell the Rainbow Collar');
  await closeAll(); await t.home('yard');
  await setBook(39); await openJ('coats'); await p.waitForSelector('.ctop'); s = await S();
  ok(!!s.coatRewards[40] && s.decor && s.decor['Giant Crayon Box'] && s.decor['Giant Crayon Box'].out === true, '40 coats: Giant Crayon Box yard decoration');
  const got40 = s.decor['Giant Crayon Box'].got;
  await closeAll(); await openJ('coats'); await p.waitForSelector('.ctop'); s = await S();
  ok(s.decor['Giant Crayon Box'].got === got40, '40: given once');
  await closeAll();
  await setBook(49); await openJ('coats'); await p.waitForSelector('.ctop'); s = await S();
  ok(!!s.coatRewards[50] && !!s.titles['Master Breeder'], '50 coats: Master Breeder is in S.titles too');
  ok(await p.locator('.cmile').count() === 7 && /Rainbow Collar/.test(await p.textContent('.cmiles')), 'reward track shows 7 steps');
  await closeAll();

  sec('Sparkle Meter jar');
  await t.patch({ pupsSinceSparkle: 7 });
  await openJ('coats'); await p.waitForSelector('.cjar');
  ok(await p.getAttribute('.cjar', 'data-fill') === '7' && /7 \/ 24/.test(await p.textContent('.cjar')), 'jar fill 7 / 24');
  ok(/guaranteed by puppy 24/.test(await p.textContent('.cjar')), 'jar caption');
  ok(await p.locator('.cjar-art svg').count() >= 1, 'jar art drawn'); await t.SH('coats');
  await closeAll();
  await t.patch({ pupsSinceSparkle: 24 }); await openJ('coats'); await p.waitForSelector('.cjar');
  ok(await p.getAttribute('.cjar', 'data-fill') === '24', 'jar full at 24'); await closeAll();
  await t.patch({ pupsSinceSparkle: 0 });

  sec('Breeds & Mixes strip');
  const key = s0.dog.key;
  await t.patch({ tree: { sled1: { id: 'sled1', name: 'Noodle Roll', key: 'corgi', sex: 'male', status: 'npc', mix: { a: 'corgi', b: 'husky', name: 'Sled Noodle', grand: 'Sled Noodle' }, anc: { corgi: 0.375, husky: 0.375, dachs: 0.25 }, parents: null } } });
  await openJ('coats'); await p.waitForSelector('.cmixes');
  ok(await p.locator('.cmixes .mchip.grand.found').filter({ hasText: 'Sled Noodle' }).count() === 1, 'Sled Noodle chip is found');
  ok(await p.locator('.cmixes .mchip.grand.unk').count() === 3, 'the other 3 grand-mixes are "?"');
  ok(await p.locator('.cmixes .mchip.breed.found').count() >= 3, 'found breeds listed (own breed, corgi, husky, dachs)');
  ok(await p.locator('.cmixes .mchip.breed').count() >= 10, 'all breeds have a chip');
  await closeAll();

  sec('titles: toggle on the name tag, old Treasure Legend migrated');
  await ev(() => { const S = window.__paw.S; S.titles = {}; S.coatRewards = {}; S.coatBook = {}; S.title = 'Treasure Legend'; });
  await openJ('profile'); await p.waitForSelector('.pf-titles');
  s = await S(); ok(!!s.titles['Treasure Legend'], 'Treasure Legend moved into S.titles');
  await ev(() => window.__paw.titleGive('Gene Detective')); s = await S();
  ok(s.title === 'Treasure Legend' && !!s.titles['Gene Detective'], 'titleGive adds once and keeps the title that is shown');
  await ev(() => window.__paw.titleGive('Gene Detective')); s = await S(); ok(Object.keys(s.titles).length === 2, 'titleGive twice: still one entry');
  await closeAll(); await openJ('profile'); await p.waitForSelector('.pf-titles .ptitle');
  ok(await p.locator('.ptitle').count() === 2, 'Profile lists 2 titles');
  await p.click('[data-jtitle="Gene Detective"]'); await p.waitForSelector('.ptitle.on[data-jtitle="Gene Detective"]');
  ok((await S()).title === 'Gene Detective' && await p.textContent('#hudTitle') === 'Gene Detective', 'one click shows the title on the name tag');
  await p.click('[data-jtitle="Gene Detective"]'); await t.until(() => !document.querySelector('.ptitle.on'));
  ok(!(await S()).title && await ev(() => document.getElementById('hudTitle').hidden), 'second click hides it');
  await t.SH('profile_titles');
  await closeAll();

  sec('Profile: ancestry line and Proud Mum');
  await t.patch({ dog: { anc: null } }); // v2.1 merge: BREED backfills anc on load, and patch() merges objects
  await t.patch({ dog: { anc: { corgi: 0.75, husky: 0.25 }, proud: '2026-02-02' } });
  await openJ('profile'); await p.waitForSelector('.profile');
  ok(/Corgi, 1\/4 Husky/.test(await p.textContent('.ancline')), 'ancestry line: Corgi, 1/4 Husky');
  ok(await p.locator('.titlebadge.proud').count() === 1, 'Proud Mum badge'); await t.SH('profile');
  await closeAll();

  sec('Family tab: Find a partner');
  await t.patch({ dog: { born: await ago(400), fixed: false } });
  await openJ('family'); await p.waitForSelector('.famwrap');
  ok(await p.locator('.fpartner').count() === 1, 'Find a partner on a grown-up dog at home');
  await p.click('.fpartner'); await t.until(() => !document.querySelector('.panel.journal'), null, 4000);
  ok(await ev(() => !document.querySelector('.panel.journal') && !document.getElementById('modal').hidden), 'it closes the Journal and opens the Playdates popup');
  await closeAll();
  await t.patch({ dog: { fixed: true } }); await openJ('family'); await p.waitForSelector('.famwrap');
  ok(await p.locator('.fpartner').count() === 0, 'hidden for a fixed dog'); await closeAll();
  await t.patch({ dog: { fixed: false, born: await ago(1) } }); await openJ('family'); await p.waitForSelector('.famwrap');
  ok(await p.locator('.fpartner').count() === 0, 'hidden for a puppy'); await closeAll();
  await t.patch({ dog: { born: await ago(400) } });

  sec('family rewards: gen3 and gen5');
  await ev(() => { const S = window.__paw.S; S.famRewards = {}; delete S.portrait; delete S.decor; });
  const T3 = { g1: { id: 'g1', name: 'Gran', key: 'corgi', sex: 'female', status: 'npc', parents: null }, m1: { id: 'm1', name: 'Mum', key: 'corgi', sex: 'female', status: 'npc', parents: { dam: 'g1', sire: null } } };
  await t.patch({ tree: T3, dog: { parents: { dam: 'm1', sire: null } } });
  await openJ('family'); await p.waitForSelector('.famwrap'); s = await S();
  ok(!!s.famRewards.gen3 && s.decor && s.decor['Family Photo Frame'] && s.decor['Family Photo Frame'].out === true, '3 generations: Family Photo Frame');
  ok(s.portrait && s.portrait.ids.includes(me) && s.portrait.ids.length <= 4, 'portrait set to that line when there was none');
  ok(!s.famRewards.gen5 && !s.titles['Great-Great-Granddog'], 'no gen5 title yet');
  await closeAll();
  await ev(() => { const S = window.__paw.S; S.portrait = { date: '2020-01-01', ids: ['keep'] }; delete S.famRewards.gen3; delete S.decor; });
  await ev(() => window.__paw.jrFamCheck()); s = await S();
  ok(s.famRewards.gen3 && s.portrait.ids.join() === 'keep', 'an existing portrait is kept');
  const T5 = { g2: { id: 'g2', name: 'GreatGran', key: 'corgi', sex: 'female', status: 'npc', parents: null }, g1: { id: 'g1', name: 'Gran', key: 'corgi', sex: 'female', status: 'npc', parents: { dam: 'g2', sire: null } }, g0: { id: 'g0', name: 'Old Gran', key: 'corgi', sex: 'female', status: 'npc', parents: { dam: 'g1', sire: null } } };
  await ev((o) => { const S = window.__paw.S; Object.assign(S.tree, o.T); S.tree.g1.parents = { dam: 'g2', sire: null }; S.tree.m1.parents = { dam: 'g0', sire: null }; }, { T: T5 });
  await ev(() => window.__paw.jrFamCheck()); s = await S();
  ok(!!s.famRewards.gen5 && !!s.titles['Great-Great-Granddog'], '5 generations: Great-Great-Granddog'); const gen5 = s.famRewards.gen5;
  await ev(() => window.__paw.jrFamCheck()); s = await S(); ok(s.famRewards.gen5 === gen5, 'gen5 given once');

  sec('Glitter Legend');
  await ev(() => { const S = window.__paw.S; S.sparkleBook = {}; window.PawGenes.BREEDS.slice(0, 9).forEach((k) => { S.sparkleBook[k] = '2026-03-03'; }); });
  await ev(() => window.__paw.jrFamCheck()); s = await S(); ok(!s.titles['Glitter Legend'], '9 of 10 Sparkle breeds: not yet');
  await ev(() => { const S = window.__paw.S; S.sparkleBook[window.PawGenes.BREEDS[9]] = '2026-03-03'; window.__paw.jrFamCheck(); }); s = await S();
  ok(!!s.famRewards.glitter && !!s.titles['Glitter Legend'], 'Sparkle pup of all 10 breeds: Glitter Legend');

  sec('pen-pal schedule: day 14 = 40 coins, day 30 = 80 coins, birthdays');
  const fam = { id: 'tanaka', name: 'the Tanakas', where: 'by the bakery' };
  const pup = (o) => Object.assign({ id: 'pp1', name: 'Bean', key: 'corgi', sex: 'female', genes: { B: ['B', 'B'], D: ['D', 'D'], E: ['E', 'E'], S: ['S', 'S'], M: ['m', 'm'], Bl: ['bl', 'bl'] }, parents: null, family: fam, mix: null, sparkle: false }, o);
  const mail = async (id) => (await S()).mail.filter((m) => m.id === id);
  await ev(() => { const S = window.__paw.S; S.mail = []; S.penpals = {}; S.mailCards = {}; });
  await t.patch({ rehomed: [pup({ born: await ago(25), since: await ago(14), sparkle: true })], mailCards: { pp1: { n: 0, next: '2999-01-01' } } });
  const c0 = (await S()).coins;
  await ev(() => window.__paw.mailTick()); s = await S();
  ok(s.coins === c0 + 40, 'day 14: +40 coins'); let m14 = await mail('pp_pp1_d14');
  ok(m14.length === 1 && m14[0].gift && m14[0].gift.coins === 40 && m14[0].gift.claimed, 'day 14 photo postcard carries the 40 coin gift');
  ok(!s.mail.some((m) => m.id === 'pp_pp1_d30'), 'no day 30 card yet');
  const b2 = await mail('pp_pp1_b2'); ok(b2.length === 1 && !b2[0].gift, 'birthday card (born 25 days ago = 2nd birthday), no gift');
  ok(!!s.penpals.tanaka, 'S.penpals gets the family on the first postcard');
  await ev(() => window.__paw.mailTick()); s = await S(); ok(s.coins === c0 + 40 && s.mail.length === 2, 'ticks again: nothing paid or sent twice');
  await t.patch({ rehomed: [pup({ born: await ago(25), since: await ago(30), sparkle: true })] });
  await ev(() => window.__paw.mailTick()); s = await S();
  ok(s.coins === c0 + 40 + 80 && (await mail('pp_pp1_d30')).length === 1, 'day 30: +80 coins, once');
  ok((await mail('pp_pp1_d14')).length === 1 && s.mailCards.pp1.paid.d14 && s.mailCards.pp1.paid.d30, 'paid marks kept on the schedule record');
  await ev(() => window.__paw.mailTick()); s = await S(); ok(s.coins === c0 + 120, 'still no double pay');
  await t.patch({ rehomed: [pup({ born: await ago(37), since: await ago(30), sparkle: true })] });
  await ev(() => window.__paw.mailTick()); s = await S();
  ok((await mail('pp_pp1_b3')).length === 1 && s.coins === c0 + 120, '3rd birthday (36 days from born): a card, no coins');
  await t.sleep(200);

  sec('glitter postcard + album');
  await t.home('yard');
  await p.click('#mailboxG', { position: { x: 40, y: 30 } }); await p.waitForSelector('.panel.mailbox');
  await p.locator('.mb-item.k-postcard').first().click(); await p.waitForSelector('.letter.k-postcard');
  ok(await p.locator('.letter .pc.pc-spk').count() === 1, 'Sparkle pup postcard has the glitter border'); await t.SH('mailbox_glitter');
  await ev(() => { document.documentElement.dataset.motion = 'off'; });
  ok(await ev(() => getComputedStyle(document.querySelector('.pc.pc-spk')).animationName === 'none'), 'glitter is static when motion is off');
  await ev(() => { delete document.documentElement.dataset.motion; });
  await p.click('[data-mbt=album]'); await p.waitForSelector('.album');
  ok(await p.locator('.al-slot').count() === 12 && await p.locator('.al-slot.found').count() === 1, 'album: 12 slots, 1 found');
  ok(/the Tanakas/.test(await p.textContent('.al-slot.found')) && /1 \/ 12/.test(await p.textContent('.al-head')), 'found slot shows the family name');
  await t.SH('mailbox_album');
  await p.click('[data-mbt=letters]'); await p.waitForSelector('.mbox'); await closeAll();
  const ids = ['tanaka', 'reyes', 'okafor', 'lin', 'nguyen', 'patel', 'kowalski', 'abebe', 'moreno', 'haddad', 'sato'];
  await ev((ids) => { const S = window.__paw.S; S.penpals = {}; ids.forEach((i) => { S.penpals[i] = '2026-04-04'; }); S.famRewards.penpals = null; delete S.famRewards.penpals; }, ids);
  s = await S(); ok(!s.titles['Friend of Paw Haven'], '11 families: no title');
  await t.patch({ rehomed: [pup({ id: 'pp2', name: 'Fig', born: await ago(3), since: await ago(1), family: { id: 'obrien', name: "the O'Briens", where: 'up on Hill Lane' } })], mailCards: { pp2: { n: 0, next: await ago(0) } } });
  await ev(() => window.__paw.mailTick()); s = await S();
  ok(!!s.penpals.obrien && !!s.famRewards.penpals && !!s.titles['Friend of Paw Haven'], 'postcard from all 12 families: Friend of Paw Haven');
  await p.click('#mailboxG', { position: { x: 40, y: 30 } }); await p.waitForSelector('.panel.mailbox'); await p.click('[data-mbt=album]'); await p.waitForSelector('.album');
  ok(await p.locator('.al-slot.found').count() === 12, 'album: all 12 slots found'); await closeAll();

  sec('old save: no new fields');
  await ev(() => { const S = window.__paw.S; delete S.titles; delete S.penpals; delete S.famRewards; delete S.decor; });
  await openJ('profile'); await p.waitForSelector('.profile'); await closeAll();
  await openJ('coats'); await p.waitForSelector('.ctop'); await closeAll();
  ok(true, 'journal opens with every v2.1 field missing');
}, { timeout: 480000 });
